manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: vrifmus
      url-base: https://github.com/vrifmus
    - name: ggrocer
      url-base: https://github.com/greengrocer98
  projects:
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: badjeff
      revision: main
    - name: zmk-status_led
      remote: vrifmus
      revision: main
    - name: zmk-vfx-indicator
      remote: ggrocer
      revision: main
  self:
    path: config